language: go
go: 1.12.x
install:
- go get -v github.com/gohugoio/hugo
- npm install -g travis-ci-cloudfront-invalidation
script:
- hugo version
- cd site
- hugo -D
- cat public/index.html
deploy:
  provider: s3
  bucket: gavincabbage.com
  acl: public_read
  local_dir: public
  skip_cleanup: true
  on:
    branch: master
    repo: gavincabbage/gavincabbage.com
  access_key_id: AKIAJPTD5BXSUWKLFYFQ
  secret_access_key:
    secure: ZSHpE6ROBzIkOu8MMEyXrj6+Q5Evp2LquY007/ymXxaPH3Z0wnun4kUyF01uims8Pi56OcRLycYTBV/mqDoJilNhbjtLiyxNHv40XoqaD3CRQ+aamPwr0dK4gyVfl0ECn+ma+olkr0ghl1fd44WIsfHh0eJHPxwYjdxY7sh6rrwan6YdSlzv27GnVryEYWgJvLz7nrdW9WKP+6qnCphIaxi5IVas7qxxYJZxas3LZpTGOKsjIu1Waq+TMX3yi656WbyCiBRiLmryNlwVJ588MWjrsive5yR023wE2DleTJqc4o/eiCoc3iQsliNxBSw1fvpF2445Z17SLqviSxUyBHKBP9tTym5CJx7lluxHJw5llIZn3p/Ywnn7v3LryhggCNuzjhd4MMOJcJt9y+bj5PVaF91kYVg2++Db4i+CJdN8IeTfZicKD7pFt9I1rj4LtB5eSTY7L9nEw/Sdnnt5kFXijvSt5k+/n/cEa1L66qp97EBvVoZhwhMU4oK6ieb22mDYvuzVaMnvEjgsArBFgBShJ/bfmL/s6c+AW38kL7VgpoQ0Ea3mWmOrQc8NWRw+5op2H5WlvDzTZuYtweV7rMr58wha8s7nAlxTV9QUpFKegXLZcx9JI8xgd/90HmuJhsYwSjzxYpMWoFJsEXPV+rz/vmGBmNZwFlWnM6ICS9A=
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
env:
  global:
    secure: jdv6Tdb5HdOBe21UEP9QBNMIOROZEvcdt7JSIirX2nZWbgdkuzmeJCmwd0czFlNOBB/GrgCPhqRKvVPdJ7X3BMYseofzWwb61oQxppy3tp+beAlM98piUmzyamhzu0biP8gZ34U0PwhDbh8DtfMTEbmq5JWMF9nRzBIZCrmn+VTRFLJALaepnoG/qYqUlHb7TUCwCtv9xuRKxNstl5RqLVhacVPtcTlCQ8zSIW9px1xMYofBwDxDEMq/jq5a6aq5IAAEAQlIsaSv7jwHL0eHVY6ZTU8fttUd0VFqk6fyeVlpWt8s9283H+qor7jp/tkyEHBxF7MbPQKHrF/COnpf9n5PGPoAIvFkQVzgjNcVO0FRDjaOyOnPYO8JL4C/4QE2pUL0BHIuIyVogFOE1uhbQlml+EEze7gygvkeo+Z7sfOJcJIIvLMGANdUzjTOkmxqVkhaJw1xI16TbnbvWZzm5TkxPfrX9ZaeV9elBjDuPfEpTTKqJUZk6d51xVB7G9ecfp6f3s+eD2XnYJ3equ26gZXj8aLsoXcjFarHpLu0Y1fDGPAIaJYyU+GwmDh2przMkgNHzwDKyL2VliAaO3xmYPars/B8cmsCd3xa1ljrv3Tbo1PS6hovuNWVIjJTnZBU0dRADgfpgOj7J4Sc7WYAzzfIgsDdJHM1Fjt6+Z6WZ3c=
