baseURL = "https://gavincabbage.com/"
languageCode = "en-us"
title = "Gavin Cabbage"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "edit"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3