baseURL = "https://gavincabbage.com/"
languageCode = "en-us"
title = "Gavin Cabbage"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-147076716-1"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Coding and cooking all the things"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 7
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Projects"
url = "/tags/projects"
weight = 4

[[menu.main]]
name = "Cooking"
url = "/tags/cooking"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

[permalinks]
posts = "/:title/"

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/gavincabbage"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gavincabbage"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/gavin-cabbage-9b31b376"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
   tag = "tags"
