baseURL = "https://gavincabbage.com/"
languageCode = "en-us"
title = "Gavin Cabbage"

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/posts/about-me/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/tags/projects/"
    weight = 4
  [[menu.main]]
    name = "Cooking"
    url = "/tags/cooking/"
    weight = 5
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6