baseURL = "https://gavincabbage.com/"
languageCode = "en-us"
title = "Gavin Cabbage"

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "About"
    url = "/posts/about-me/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Topics"
    url = "/tags/"
    weight = 3