version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context: aws

jobs:
  build_and_deploy:
    docker:
      - image: alpine:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/dist
    steps:
      - run:
        name: install
        command: |
          apk update
          apk add --update git hugo python python-dev py-pip build-base
          pip install awscli
      - checkout
      - run:
        name: build
        command: cd src && HUGO_ENV=production hugo -v -d ${HUGO_BUILD_DIR}
      - run:
        name: htmlproofer
        command: |
          htmlproofer ${HUGO_BUILD_DIR} --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
      - run:
        name: deploy
        command: |
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            aws s3 sync ${HUGO_BUILD_DIR} s3://gavincabbage.com --delete && \
            aws cloudfront create-invalidation \
              --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION} --paths /*
          else
            echo "Not master branch, dry run only"
          fi